-- ============================================================
--  Score categories: chairs define their own, each with a cap
--  Run ONCE:  supabase.cmd db query --linked --file ...
--
--  Replaces the 10 categories hardcoded in TurnLogger.jsx
--  (Speech, Caucus, Diplomacy, Resolution, Amendment, POI,
--  Opening Speech, Closing Speech, Moderated/Unmoderated Caucus).
--
--  Categories are scoped to a committee, so every committee picks
--  its own names and limits.
--
--  Two guarantees, enforced in the database because the anon key
--  has full write access:
--    1. a score can only be logged under a declared category
--    2. a delegate's total for a category cannot exceed max_points
--
--  Safe to re-run: every statement is idempotent.
-- ============================================================

BEGIN;

-- ---------- 1. Clear the old built-in categories ----------
DELETE FROM public.scores
WHERE category IN (
  'Speech', 'Caucus', 'Diplomacy', 'Resolution', 'Amendment', 'POI',
  'Opening Speech', 'Closing Speech', 'Moderated Caucus', 'Unmoderated Caucus'
);

-- ---------- 2. Categories table ----------
CREATE TABLE IF NOT EXISTS public.score_categories (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  committee_id bigint NOT NULL,
  name         TEXT NOT NULL,
  max_points   NUMERIC(10,2) NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT score_categories_single_committee_link
    FOREIGN KEY (committee_id) REFERENCES public.committees(id) ON DELETE CASCADE,
  CONSTRAINT score_categories_committee_name_unique
    UNIQUE (committee_id, name),
  CONSTRAINT score_categories_max_points_positive
    CHECK (max_points > 0)
);

CREATE INDEX IF NOT EXISTS idx_score_categories_committee
  ON public.score_categories(committee_id);

-- ---------- 3. scores.category is now always supplied by the app ----------
ALTER TABLE public.scores ALTER COLUMN category DROP DEFAULT;
ALTER TABLE public.scores ALTER COLUMN category SET NOT NULL;

-- ---------- 4. Realtime ----------
ALTER TABLE public.score_categories REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.score_categories;
  EXCEPTION WHEN duplicate_object THEN NULL;
            WHEN undefined_object   THEN NULL;
  END;
END $$;

-- ---------- 5. Row Level Security ----------
-- Same open policy as the other tables. This is a known gap, not an
-- oversight: tighten it once Supabase Auth is in place.
ALTER TABLE public.score_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.score_categories;
CREATE POLICY "Allow full access for anonymous users" ON public.score_categories
  FOR ALL USING (true) WITH CHECK (true);

-- ---------- 6. updated_at ----------
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_score_categories_updated_at ON public.score_categories;
CREATE TRIGGER update_score_categories_updated_at
  BEFORE UPDATE ON public.score_categories
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ---------- 7. Enforcement ----------
CREATE OR REPLACE FUNCTION public.enforce_score_category_limit()
RETURNS TRIGGER AS $$
DECLARE
  deleg_committee bigint;
  cat_max         NUMERIC(10,2);
  already_earned  NUMERIC(14,2);
BEGIN
  SELECT committee_id INTO deleg_committee
    FROM public.delegates
   WHERE id = NEW.delegate_id;

  IF deleg_committee IS NULL THEN
    RAISE EXCEPTION 'Cannot score delegate %: no such delegate', NEW.delegate_id;
  END IF;

  SELECT max_points INTO cat_max
    FROM public.score_categories
   WHERE committee_id = deleg_committee
     AND name = trim(NEW.category)
   LIMIT 1;

  IF cat_max IS NULL THEN
    RAISE EXCEPTION
      'Category "%" is not set up for this committee. Add it under Scoring Categories first.',
      trim(NEW.category);
  END IF;

  SELECT COALESCE(SUM(points), 0) INTO already_earned
    FROM public.scores
   WHERE delegate_id = NEW.delegate_id
     AND category = NEW.category
     AND (TG_OP = 'INSERT' OR id IS DISTINCT FROM NEW.id);

  -- Only a positive entry can push someone over the ceiling. A negative
  -- entry is a correction, and stays allowed even when they are already
  -- over because the chair lowered the limit afterwards.
  IF NEW.points > 0 AND already_earned + NEW.points > cat_max THEN
    RAISE EXCEPTION
      'Limit for "%" is % points. % already earned, so +% would reach %. Remove some points first.',
      trim(NEW.category), cat_max, already_earned, NEW.points, already_earned + NEW.points;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS enforce_score_category_limit ON public.scores;
CREATE TRIGGER enforce_score_category_limit
  BEFORE INSERT OR UPDATE OF delegate_id, category, points ON public.scores
  FOR EACH ROW EXECUTE FUNCTION public.enforce_score_category_limit();

COMMIT;

-- ---------- Verify ----------
-- SELECT column_name, data_type, is_nullable, column_default
--   FROM information_schema.columns
--  WHERE table_schema = 'public' AND table_name = 'score_categories'
--  ORDER BY ordinal_position;
--
-- SELECT count(*) FROM public.scores;   -- should be 0 after the wipe
