-- ============================================================
--  Fix scores: add an id default and the FK to delegates
--  Run in Supabase -> SQL Editor
--
--  Current state (verified):
--    id bigint NOT NULL        <-- no default, app never sends it
--    delegate_id bigint NOT NULL
--    category text NOT NULL
--    points numeric NOT NULL
--    note / created_at / updated_at fine
--    no foreign key to delegates
--
--  Fix: rebuild with id as an IDENTITY column + FK constraint,
--  copying the existing row(s) across. delegates.id is bigint
--  (confirmed by the earlier 42804 type error), so bigint is used.
-- ============================================================

BEGIN;

-- 1. Stash the existing rows so nothing is lost
DROP TABLE IF EXISTS public.scores_stash;
CREATE TABLE public.scores_stash AS
  SELECT id, delegate_id, category, points, note, created_at, updated_at
  FROM public.scores;

-- 2. Rebuild with a real identity column and FK.
--    The view must go first - it depends on scores, so the DROP
--    would fail with 2BP01 if we tried to drop scores underneath it.
DROP VIEW IF EXISTS public.score_totals;
DROP TABLE IF EXISTS public.scores;

CREATE TABLE public.scores (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegate_id bigint NOT NULL,
  category    text NOT NULL DEFAULT 'Speech',
  points      numeric(10,2) NOT NULL DEFAULT 0,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT scores_single_delegate_link
    FOREIGN KEY (delegate_id) REFERENCES public.delegates(id) ON DELETE CASCADE
);

-- 3. Restore rows whose delegate_id actually exists in delegates.
--    Rows pointing at a non-existent delegate are skipped rather than
--    failing the whole transaction - the notice reports what happened.
DO $$
DECLARE
  restored integer;
  skipped  integer;
BEGIN
  INSERT INTO public.scores (id, delegate_id, category, points, note, created_at, updated_at)
  SELECT s.id, s.delegate_id, s.category, s.points, s.note, s.created_at, s.updated_at
  FROM public.scores_stash s
  WHERE EXISTS (SELECT 1 FROM public.delegates d WHERE d.id = s.delegate_id);

  GET DIAGNOSTICS restored = ROW_COUNT;

  SELECT count(*) INTO skipped FROM public.scores_stash WHERE skipped > 0;

  RAISE NOTICE 'Restored % row(s); % skipped (no matching delegate)',
    restored, (SELECT count(*) FROM public.scores_stash) - restored;
END $$;

-- 4. Advance the identity sequence past the restored ids,
--    otherwise the next insert collides with an existing id
SELECT setval(
  pg_get_serial_sequence('public.scores', 'id'),
  COALESCE((SELECT max(id) FROM public.scores), 0) + 1,
  false
);

DROP TABLE IF EXISTS public.scores_stash;

-- 5. Realtime
ALTER TABLE public.scores REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.scores;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- 6. Row Level Security
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.scores;
CREATE POLICY "Allow full access for anonymous users" ON public.scores
  FOR ALL USING (true) WITH CHECK (true);

-- 7. View
DROP VIEW IF EXISTS public.score_totals;
CREATE VIEW public.score_totals AS
SELECT
  d.id AS delegate_id,
  d.name,
  d.country,
  d.grade,
  d.role,
  d.committee_id,
  c.name AS committee_name,
  COALESCE(SUM(s.points), 0) AS total_score
FROM public.delegates d
LEFT JOIN public.committees c ON c.id = d.committee_id
LEFT JOIN public.scores s ON s.delegate_id = d.id
GROUP BY d.id, d.name, d.country, d.grade, d.role, d.committee_id, c.name;

COMMIT;

-- ---------- Verify ----------
-- SELECT column_name, data_type, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'scores' ORDER BY ordinal_position;