-- ============================================================
--  Rebuild scores, matching whatever type delegates.id actually is
--  Run in Supabase -> SQL Editor
--
--  Why this version is different: delegates.id is `bigint` in your
--  database (not `uuid` like schema.sql assumes), so a hard-coded
--  uuid column fails with:
--    42804: Key columns "delegate_id" and "id" are of incompatible
--           types: uuid and bigint
--
--  This script reads the real type and builds the table to match, so
--  it works whether your ids are bigint or uuid.
--
--  SAFE BY DESIGN: aborts if scores already contains rows.
-- ============================================================

BEGIN;

-- 1. Safety guard - never drop data by accident
DO $$
DECLARE
  row_count integer;
BEGIN
  SELECT count(*) INTO row_count FROM public.scores;
  IF row_count > 0 THEN
    RAISE EXCEPTION
      'scores has % rows. Refusing to drop them. Run supabase/diagnose_scores.sql and migrate instead.',
      row_count;
  END IF;
END $$;

DROP TABLE IF EXISTS public.scores;

-- 2. Rebuild using the same id type as delegates
DO $$
DECLARE
  id_type      text;
  id_column_ddl text;
BEGIN
  SELECT data_type INTO id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'delegates' AND column_name = 'id';

  IF id_type IS NULL THEN
    RAISE EXCEPTION 'Could not find public.delegates.id - is the delegates table named correctly?';
  END IF;

  IF id_type = 'uuid' THEN
    id_column_ddl := 'uuid DEFAULT gen_random_uuid()';
  ELSIF id_type IN ('bigint', 'integer', 'smallint') THEN
    id_column_ddl := id_type || ' GENERATED BY DEFAULT AS IDENTITY';
  ELSE
    RAISE EXCEPTION 'Unexpected delegates.id type: %', id_type;
  END IF;

  RAISE NOTICE 'delegates.id is % - building scores to match', id_type;

  EXECUTE format($ddl$
    CREATE TABLE public.scores (
      id          %2$s PRIMARY KEY,
      delegate_id %1$s NOT NULL,
      category    TEXT NOT NULL DEFAULT 'Speech',
      points      NUMERIC(10,2) NOT NULL DEFAULT 0,
      note        TEXT,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
      CONSTRAINT scores_single_delegate_link
        FOREIGN KEY (delegate_id) REFERENCES public.delegates(id) ON DELETE CASCADE
    )
  $ddl$, id_type, id_column_ddl);
END $$;

-- 3. Realtime - full old row on UPDATE/DELETE
ALTER TABLE public.scores REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.scores;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- 4. Row Level Security
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.scores;
CREATE POLICY "Allow full access for anonymous users" ON public.scores
  FOR ALL USING (true) WITH CHECK (true);

-- 5. Rebuild the convenience view against the new table
DROP VIEW IF EXISTS public.score_totals;
CREATE VIEW public.score_totals AS
SELECT
  d.id AS delegate_id,
  d.name,
  d.country,
  d.grade,
  d.role,
  d.committee_id,
  c.name AS committee_name,
  COALESCE(SUM(s.points), 0) AS total_score
FROM public.delegates d
LEFT JOIN public.committees c ON c.id = d.committee_id
LEFT JOIN public.scores s ON s.delegate_id = d.id
GROUP BY d.id, d.name, d.country, d.grade, d.role, d.committee_id, c.name;

COMMIT;

-- ---------- Verify ----------
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'scores' ORDER BY ordinal_position;