-- ============================================================
--  MUN Conference Manager — database schema
--  Supabase -> SQL Editor
--
--  IMPORTANT - ID TYPES
--  This file uses bigint identity keys, which is what the live
--  database actually has. An earlier draft assumed uuid, which did
--  not match and caused errors like:
--    42804: Key columns "delegate_id" and "id" are of incompatible
--           types: uuid and bigint
--  Do not change these to uuid unless you also migrate every live row.
--
--  Running this against the existing database is safe: all CREATE
--  TABLE / CREATE INDEX / CREATE TRIGGER statements are IF NOT EXISTS,
--  so existing tables and data are left untouched.
--
--  For a brand new database, run this file from the start.
-- ============================================================

-- ---------- Committees ----------
CREATE TABLE IF NOT EXISTS public.committees (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- ---------- Delegates ----------
CREATE TABLE IF NOT EXISTS public.delegates (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  grade        TEXT,
  committee_id bigint NOT NULL,
  country      TEXT,
  role         TEXT NOT NULL DEFAULT 'Delegate',
  notes        TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  -- Explicitly named so PostgREST embeds can pin it with
  -- `committees!delegates_single_committee_link (...)`
  CONSTRAINT delegates_single_committee_link
    FOREIGN KEY (committee_id) REFERENCES public.committees(id) ON DELETE CASCADE
);

-- ---------- Scores ----------
CREATE TABLE IF NOT EXISTS public.scores (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegate_id bigint NOT NULL,
  category    TEXT NOT NULL DEFAULT 'Speech',
  points      NUMERIC(10,2) NOT NULL DEFAULT 0,
  note        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT scores_single_delegate_link
    FOREIGN KEY (delegate_id) REFERENCES public.delegates(id) ON DELETE CASCADE
);

-- ---------- Indexes ----------
CREATE INDEX IF NOT EXISTS idx_delegates_committee ON public.delegates(committee_id);
CREATE INDEX IF NOT EXISTS idx_delegates_grade ON public.delegates(grade);
CREATE INDEX IF NOT EXISTS idx_scores_delegate ON public.scores(delegate_id);
CREATE INDEX IF NOT EXISTS idx_scores_category ON public.scores(category);

-- ---------- Realtime ----------
-- REPLICA IDENTITY FULL makes DELETE payloads include the full old row.
-- The app listens on 'delegates' and 'scores' via postgres_changes.
ALTER TABLE public.committees REPLICA IDENTITY FULL;
ALTER TABLE public.delegates  REPLICA IDENTITY FULL;
ALTER TABLE public.scores     REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.delegates;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.scores;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- ---------- Row Level Security ----------
ALTER TABLE public.committees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delegates  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scores     ENABLE ROW LEVEL SECURITY;

-- Open access for anonymous conference use.
-- A published Vercel URL plus these policies means anyone can read and
-- rewrite all three tables. Add Supabase Auth and tighten these before
-- exposing the app outside a trusted school network.
DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.committees;
DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.delegates;
DROP POLICY IF EXISTS "Allow full access for anonymous users" ON public.scores;

CREATE POLICY "Allow full access for anonymous users" ON public.committees
  FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for anonymous users" ON public.delegates
  FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow full access for anonymous users" ON public.scores
  FOR ALL USING (true) WITH CHECK (true);

-- ---------- updated_at triggers ----------
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_committees_updated_at ON public.committees;
CREATE TRIGGER update_committees_updated_at
  BEFORE UPDATE ON public.committees
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_delegates_updated_at ON public.delegates;
CREATE TRIGGER update_delegates_updated_at
  BEFORE UPDATE ON public.delegates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_scores_updated_at ON public.scores;
CREATE TRIGGER update_scores_updated_at
  BEFORE UPDATE ON public.scores
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ---------- Convenience view: running totals ----------
DROP VIEW IF EXISTS public.score_totals;
CREATE VIEW public.score_totals AS
SELECT
  d.id AS delegate_id,
  d.name,
  d.country,
  d.grade,
  d.role,
  d.committee_id,
  c.name AS committee_name,
  COALESCE(SUM(s.points), 0) AS total_score
FROM public.delegates d
LEFT JOIN public.committees c ON c.id = d.committee_id
LEFT JOIN public.scores s ON s.delegate_id = d.id
GROUP BY d.id, d.name, d.country, d.grade, d.role, d.committee_id, c.name;

-- ============================================================
--  Reference: grade values used by the app
--  Stored verbatim in delegates.grade, so these must match
--  src/lib/grades.js GRADE_LEVELS exactly.
-- ============================================================
--  'Grade 3'  'Grade 4'  'Grade 5'  'Grade 6'  'Grade 7'
--  '8 Matric' '9 Matric' '10 Matric'
--  'Year 1'   'Year 2'   'Year 3'
-- ============================================================

-- ============================================================
--  Reference: roles used by the app (src/lib/utils.js ROLES)
--  Only 'Delegate' represents a nation. Every other role is staff
--  and is excluded from the scoreboard, and does not require a
--  country.
-- ============================================================
--  'Delegate'  'Chair'  'Vice Chair'  'Rapporteur'  'Observer'  'Gavel'
-- ============================================================